name: Push to S3
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Upload files
        uses: axazara/easy-s3-upload-github-action@main
        env:
          FILE: /app/
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_DESTINATION: ${{ github.event.repository.name }}
          #S3_ACL: 'public-read'
          S3_PREFIX: 'repositories/'
